FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
# We copy it separately to take advantage of Docker's layer caching
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
# This includes the api.py and the models directory
COPY ./src/model_serving .

# Expose the port that the API will run on
EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]